package lk.ijse.computerShop.navigation;
/* 
    @author Sachi_S_Bandara
    @created 11/3/2023 - 8:31 PM 
*/

public enum Routes {
    ADDCUSTOMER, ADDEMPLOYEE, UPDATEEMPLOYEE, DASHBOARD, CUSTOMER, EMPLOYEE, LOGIN, ORDER, UPDATECUSTOMER, SUPPLIER, SERVICE, ATTENDANCE, SALARY, PLACEORDERSELECT, BUYINGORDER, SELLINGORDER, SETTING, ADDSUPPLIER, UPDATESUPPLIER, ADDITEM, LOWSTOCK, ITEM
}
